### ISSUE TITLE
Define submission format

### ISSUE THREAD

**Issue by awortmann** [mleworkshop/mle-organization#10]
Current, we call for 5-10 pages LNCS. 

The technical track will use ACM conference style. Should we match that? Would it still be 5-10 pages then?

**Comment by richetl** [comment]
I think we should match the conference style. For ACM I would think 6 or 8 would be about right, if I’m remember correctly.

**Comment by szschaler** [comment]
Agreed.

Steffen

Dr. rer. nat. Steffen Zschaler AHEA

Senior Lecturer
King's College London
Department of Informatics

Visiting Scientist
The Francis Crick Institute

Email szschaler@acm.org
Phone +44 (020) 7848 1513
WWW   www.steffen-zschaler.de

**Comment by awortmann** [comment]
Changed it to 4 (short) and 8 (full)

**Comment by szschaler** [comment]
Not happy: the call for workshops asks that papers should be at least 5 pages so that they can be included in the overall publication. Can we up the short papers to 5 pages?

**Comment by szschaler** [comment]
Alternatively, why do we make the distinction at all given that this is a workshop?

**Comment by richetl** [comment]
I was about to ask the same thing… it’s a workshop. Can we just say 6 pages for everything?

**Comment by awortmann** [comment]
We can try that(although we should specify a minimal length): feel free to refine and update the document

**Comment by szschaler** [comment]
Yes, but at MODELS, a 5 or 6-page workshop paper doesn't strike me as bad.

**Comment by awortmann** [comment]
Done
