### ISSUE TITLE
Add PC to CfP

### ISSUE THREAD

**Issue by szschaler** [mleworkshop/mle-organization#13]

**Comment by awortmann** [comment]
Draft at https://github.com/mleworkshop/mle-organization/blob/master/2020/CfP.txt

**Comment by szschaler** [comment]
You sure about Erwan?

**Comment by richetl** [comment]
It says he accepted in easychair

**Comment by szschaler** [comment]
My bad.

Steffen

Dr. rer. nat. Steffen Zschaler AHEA

Senior Lecturer
King's College London
Department of Informatics

Visiting Scientist
The Francis Crick Institute

Email szschaler@acm.org
Phone +44 (020) 7848 1513
WWW   www.steffen-zschaler.de
